/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RBAC } from "./RBAC";
export * as factories from "./factories";
export { RBAC__factory } from "./factories/RBAC__factory";
